# -*- encoding : utf-8 -*-
omniauth:
  twitter:
    key: TWITTER_KEY
    secret: TWITTER_SECRET
  facebook:
    key: FACEBOOK_KEY
    secret: FACEBOOK_SECRET
  linkedin:
    key: LINKEDIN_KEY
    secret: LINKEDIN_SECRET
  37signals:
    key: 37SIGNALS_KEY
    secret: 37SIGNALS_SECRET
  github:
    key: GITHUB_KEY
    secret: GITHUB_SECRET
  google_oauth2:
    key: GOOGLE_OAUTH2_KEY
    secret: GOOGLE_OAUTH2_SECRET
  foursquare:
    key: FOURSQUARE_KEY
    secret: FOURSQUARE_SECRET
  tumblr:
    key: TUMBLR_KEY
    secret: TUMBLR_SECRET
  # campus: # For WWEDU staff only
  #   key: CAMPUS_KEY
  #   secret: CAMPUS_SECRET
  #   url: CAMPUS_URL
openid:
  store: "tmp/"

